server:
  port: 10010

spring:
#  application:
#    name: gateway # 服务名称
  cloud:
    gateway:
      # 全局的跨域配置
      globalcors:
        # 解决options请求被拦截问题
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          # 拦截的请求
          '[/**]':
            # 允许跨域的请求
            allowedOrigins: "*" # spring boot2.4以前的配置
            #allowedOriginPatterns: "*" # spring boot2.4以后的配置
            # 允许请求中携带的头信息
            allowedHeaders: "*"
            # 运行跨域的请求方式
            allowedMethods: "*"
            # 是否允许携带cookie
            alloweCredentials: true
            # 跨域检测的有效期,单位s
            maxAge: 36000
      discovery:
        locator:
          enabled: true
      routes:

        - id: ledger-service # 路由标志，必须唯一
          uri: lb://ledger-service # 路由的目标地址
          predicates: # 路由断言，判断请求是否符合规则
            - Path=/user/**   #路径断言，判断路径都否以/user开头，如果是则符合
            - Path=/ledger/** #路径断言，判断路径都否以/ledger开头，如果是则符合