server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_db_business?useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    cn.itcast: debug
  pattern:
    dataformat: MM-dd HH:mm:ss:SSS
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
